id: IF24E4C7C
ocr_import_info:
  bdrc_scan_id: W4CZ1042
  source: bdrc
  ocr_info:
    timestamp: '2022-08-25T00:00:00Z'
  batch_id: batch001
  software_id: norbuketatka
  expected_default_language: bo
  op_import_options: null
  op_import_versio: 1.0.0
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2022-08-31 09:26:20.614553+00:00
last_modified: 2022-08-25 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ1042
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3PD1002
  copyright_status: http://purl.bdrc.io/resource/CopyrightClaimed
  title: གཏེར་ཆོས། རྩ་གསུམ་གླིང་པ།
  author: གནམ་ལྕགས་རྩ་གསུམ་གཏེར་བདག་གླིང་པ།
bases:
  I1PD108815:
    source_metadata:
      id: http://purl.bdrc.io/resource/W4CZ1042
      total_pages: 687
      volume_number: 27
      volume_pages_bdrc_intro: 2
    base_file: I1PD108815.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
